server:
  port: 9091

spring:
  application:
    name: auth-service

  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
