spring:
  application:
    name: user-service
  config:
    import: "configserver:"  # ← на уровне spring!
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false #turn on later wwhen get eureka
