server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/returnaction/InterviewProject_digital-config-repo
          default-label: main  # ??? ?????, ??? ????? ???????
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false # turn on later when get eureka